export const typography = {
  fontFamily: {
    primary: '"Circular Std", system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
    accent: '"Denton", "Circular Std", system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif',
  },
  fontSize: {
    '8': '8px',
    '10': '10px',
    '12': '12px',
    '14': '14px',
    '17': '17px',
    '20': '20px',
    '24': '24px',
  },
  fontWeight: {
    book: '400',
    medium: '500',
    bold: '700',
  },
  lineHeight: {
    '12': '12px',
    '14': '14px',
    '16': '16px',
    '20': '20px',
    '22': '22px',
    '24': '24px',
    '28': '28px',
    '32': '32px',
  },
  letterSpacing: {
    '-0.5': '-0.5px',
    '-0.4': '-0.4px',
    '-0.3': '-0.3px',
    '-0.2': '-0.2px',
    '0': '0px',
    '0.3': '0.3px',
    '0.5': '0.5px',
    '1': '1px',
  },
  textStyles: {
    '17 med': {
      fontFamily: 'primary',
      fontWeight: 'medium',
      fontSize: '17',
      lineHeight: '24',
      letterSpacing: '-0.4',
    },
    '12 book': {
      fontFamily: 'primary',
      fontWeight: 'book',
      fontSize: '12',
      lineHeight: '20',
      letterSpacing: '-0.2',
    },
    '17 book': {
      fontFamily: 'primary',
      fontWeight: 'book',
      fontSize: '17',
      lineHeight: '24',
      letterSpacing: '-0.4',
    },
    '24 book': {
      fontFamily: 'primary',
      fontWeight: 'book',
      fontSize: '24',
      lineHeight: '32',
      letterSpacing: '-0.5',
    },
    '24 med': {
      fontFamily: 'primary',
      fontWeight: 'medium',
      fontSize: '24',
      lineHeight: '32',
      letterSpacing: '-0.5',
    },
    '10 book': {
      fontFamily: 'primary',
      fontWeight: 'book',
      fontSize: '10',
      lineHeight: '16',
      letterSpacing: '0',
    },
    '14 book': {
      fontFamily: 'primary',
      fontWeight: 'book',
      fontSize: '14',
      lineHeight: '22',
      letterSpacing: '-0.3',
    },
    '10 med': {
      fontFamily: 'primary',
      fontWeight: 'medium',
      fontSize: '10',
      lineHeight: '16',
      letterSpacing: '-0.2',
    },
    '20 book': {
      fontFamily: 'primary',
      fontWeight: 'book',
      fontSize: '20',
      lineHeight: '28',
      letterSpacing: '-0.5',
    },
    '20 med': {
      fontFamily: 'primary',
      fontWeight: 'medium',
      fontSize: '20',
      lineHeight: '28',
      letterSpacing: '-0.5',
    },
    'Accent - 01': {
      fontFamily: 'accent',
      fontWeight: 'medium',
      fontSize: '20',
      lineHeight: '24',
      letterSpacing: '0.3',
    },
    '8 all-caps': {
      fontFamily: 'primary',
      fontWeight: 'bold',
      fontSize: '8',
      lineHeight: '12',
      letterSpacing: '0.5',
      textTransform: 'uppercase',
    },
    '12 med': {
      fontFamily: 'primary',
      fontWeight: 'medium',
      fontSize: '12',
      lineHeight: '20',
      letterSpacing: '-0.2',
    },
    '10 all-caps': {
      fontFamily: 'primary',
      fontWeight: 'bold',
      fontSize: '10',
      lineHeight: '14',
      letterSpacing: '1',
      textTransform: 'uppercase',
    },
    '14 med': {
      fontFamily: 'primary',
      fontWeight: 'medium',
      fontSize: '14',
      lineHeight: '22',
      letterSpacing: '-0.3',
    },
  },
} as const;
